# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'myservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmyservice.proto\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\"$\n\x13SubscriptionRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x17\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2a\n\tMyService\x12%\n\x0eProcessRequest\x12\x08.Request\x1a\t.Response\x12-\n\tSubscribe\x12\x14.SubscriptionRequest\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=19
  _globals['_REQUEST']._serialized_end=42
  _globals['_RESPONSE']._serialized_start=44
  _globals['_RESPONSE']._serialized_end=70
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=72
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=108
  _globals['_MESSAGE']._serialized_start=110
  _globals['_MESSAGE']._serialized_end=133
  _globals['_MYSERVICE']._serialized_start=135
  _globals['_MYSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
